name: CI - Build, Testes e Docker

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build e testes
        run: mvn clean verify

      - name: Build da imagem Docker
        run: docker build -t notificador-backend .

      - name: Definir versão
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Login no Docker Hub
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag da imagem (versionada)
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag notificador-backend ${{ secrets.DOCKER_USERNAME }}/notificador-backend:${{ env.VERSION }}

      - name: Tag latest
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag notificador-backend ${{ secrets.DOCKER_USERNAME }}/notificador-backend:latest

      - name: Push da imagem (versionada)
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notificador-backend:${{ env.VERSION }}

      - name: Push da imagem latest
        if: startsWith(github.ref, 'refs/tags/')
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notificador-backend:latest
