name: CI - Build, Testes e Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar c√≥digo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build e testes
        run: mvn clean verify

      - name: Build da imagem Docker
        run: docker build -t notificador-backend .

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag da imagem
        run: docker tag notificador-backend ${{ secrets.DOCKER_USERNAME }}/notificador-backend:latest

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notificador-backend:latest
